# Generated by Django 2.2.2 on 2019-07-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GateWaySettingDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('down_type', models.CharField(max_length=30, verbose_name='下发类型')),
                ('down_topic', models.CharField(max_length=100, verbose_name='下发主题')),
                ('down_remark', models.CharField(max_length=100, verbose_name='主题描述')),
                ('down_num', models.IntegerField(verbose_name='下发次数')),
            ],
            options={
                'verbose_name': '网关远程配置统计',
                'verbose_name_plural': '网关远程配置统计',
                'db_table': 'gateway_setting_down',
            },
        ),
        migrations.CreateModel(
            name='GateWayStatusPub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('pub_type', models.CharField(max_length=30, verbose_name='发布类型')),
                ('pub_topic', models.CharField(max_length=100, verbose_name='发布主题')),
                ('pub_remark', models.CharField(max_length=100, verbose_name='主题描述')),
                ('pub_num', models.IntegerField(verbose_name='回应次数')),
            ],
            options={
                'verbose_name': '网关远程状态发布统计',
                'verbose_name_plural': '网关远程状态发布统计',
                'db_table': 'gateway_status_pub',
            },
        ),
    ]
