# Generated by Django 2.2.2 on 2019-11-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticemanager',
            name='notice_status',
            field=models.CharField(max_length=30, verbose_name='狀態'),
        ),
    ]
