# Generated by Django 2.2.2 on 2019-08-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wangguang', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerinfo',
            old_name='gateway_id',
            new_name='gateway_key',
        ),
    ]
