# Generated by Django 2.2.2 on 2019-11-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangguang', '0002_auto_20190805_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysinfo',
            name='sys_com',
            field=models.CharField(max_length=30, null=True, verbose_name='當前COM口'),
        ),
        migrations.AddField(
            model_name='sysinfo',
            name='sys_use_usb_num',
            field=models.IntegerField(default=4, null=True, verbose_name='系统USB使用數量'),
        ),
    ]
