# Generated by Django 2.2.2 on 2019-07-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('data_type', models.SmallIntegerField(choices=[(0, '属性'), (1, '事件'), (2, '报警')], default=0, verbose_name='子设备数据类型')),
                ('data_status', models.SmallIntegerField(choices=[(0, '未发送'), (1, '已发送')], default=0, verbose_name='数据状态')),
                ('data', models.CharField(max_length=2000, verbose_name='子设备采集数据')),
            ],
            options={
                'verbose_name': '网关子设备采集数据',
                'verbose_name_plural': '网关子设备采集数据',
                'db_table': 'gateway_subdevice_collectdata',
            },
        ),
    ]
