# Generated by Django 2.2.2 on 2019-07-18 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shebei', '0001_initial'),
        ('apidata', '0003_auto_20190718_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectdata',
            name='subdevice_id',
        ),
        migrations.AddField(
            model_name='collectdata',
            name='subdevice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shebei.SubDevice', verbose_name='子设备id'),
            preserve_default=False,
        ),
    ]
