# Generated by Django 2.2.2 on 2019-09-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0005_m5data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectdata',
            name='subdevice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectdatas', to='shebei.SubDevice', verbose_name='子设备id'),
        ),
    ]
