# Generated by Django 2.2.2 on 2019-07-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('subdevice_name', models.CharField(max_length=30, verbose_name='子设备名称')),
                ('subdevice_secret', models.CharField(default='', max_length=200, verbose_name='子设备secret')),
                ('subdevice_position', models.CharField(max_length=30, verbose_name='子设备位置')),
                ('subdevice_model', models.CharField(max_length=30, verbose_name='子设备型号')),
                ('subdevice_type', models.CharField(max_length=30, verbose_name='子设备类型')),
                ('subdevice_remark', models.CharField(max_length=50, verbose_name='子设备描述')),
                ('subdevice_online_time', models.DateTimeField(auto_now_add=True, verbose_name='最近上线时间')),
                ('subdevice_status', models.SmallIntegerField(choices=[(0, '离线'), (1, '在线')], default=0, verbose_name='子设备运行状态')),
                ('subdevice_enable', models.SmallIntegerField(choices=[(0, '未启用'), (1, '启用')], default=1, verbose_name='子设备激活使能')),
            ],
            options={
                'verbose_name_plural': '网关子设备列表信息',
                'db_table': 'gateway_subdevice_list',
                'verbose_name': '网关子设备列表信息',
            },
        ),
    ]
