# Generated by Django 2.2.2 on 2019-08-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shebei', '0002_subdevice_subdevice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdevice',
            old_name='subdevice_id',
            new_name='subdevice_key',
        ),
    ]
