# Generated by Django 2.2.2 on 2019-08-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shebei', '0003_auto_20190805_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransmitList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('transmit_type', models.SmallIntegerField(choices=[(0, 'CorePro'), (1, 'MQTT'), (2, 'Kafaka'), (3, 'DB')], default=0, verbose_name='转发类型')),
                ('transmit_status', models.SmallIntegerField(choices=[(0, '正在运行'), (1, '已禁用'), (2, '转发出错'), (3, '转发停止')], default=1, verbose_name='转发状态')),
                ('transmit_name', models.CharField(default='通道xx', max_length=30, verbose_name='转发名称')),
                ('transmit_ip', models.CharField(default='', max_length=30, verbose_name='转发ip')),
                ('transmit_port', models.CharField(default='', max_length=30, verbose_name='转发port')),
                ('transmit_username', models.CharField(default='', max_length=100, verbose_name='转发用户')),
                ('transmit_password', models.CharField(default='', max_length=100, verbose_name='转发密码')),
                ('transmit_topic', models.CharField(default='', max_length=100, verbose_name='转发主题或表')),
                ('transmit_enable', models.SmallIntegerField(choices=[(0, '未启用'), (1, '启用')], default=0, verbose_name='子设备激活使能')),
                ('subdevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shebei.SubDevice', verbose_name='子设备id')),
            ],
            options={
                'db_table': 'gateway_transmit_list',
                'verbose_name': '网关子设备数据转发通道',
                'verbose_name_plural': '网关子设备数据转发通道',
            },
        ),
    ]
