# Generated by Django 2.2.2 on 2019-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shebei', '0004_datatransmitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatransmitlist',
            name='transmit_remark',
            field=models.CharField(default='通道xx', max_length=30, verbose_name='转发描述'),
        ),
    ]
