# Generated by Django 2.2.2 on 2019-08-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shebei', '0005_datatransmitlist_transmit_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatransmitlist',
            name='transmit_number',
            field=models.IntegerField(default=0, verbose_name='子设备上传消息数'),
        ),
        migrations.AlterField(
            model_name='datatransmitlist',
            name='transmit_type',
            field=models.SmallIntegerField(choices=[(0, 'CorePro'), (1, 'MQTT'), (2, 'KAfAKA'), (3, 'DB')], default=0, verbose_name='转发类型'),
        ),
    ]
