# Generated by Django 2.2.2 on 2019-09-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shebei', '0006_auto_20190806_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransmitlist',
            name='transmit_enable',
            field=models.SmallIntegerField(choices=[(0, '关闭'), (1, '启用')], default=0, verbose_name='子设备激活使能'),
        ),
        migrations.AlterField(
            model_name='datatransmitlist',
            name='transmit_status',
            field=models.SmallIntegerField(choices=[(0, '正在运行'), (1, '已禁用'), (2, '运行异常'), (3, '转发停止')], default=1, verbose_name='转发状态'),
        ),
        migrations.AlterField(
            model_name='datatransmitlist',
            name='transmit_type',
            field=models.SmallIntegerField(choices=[(0, 'CorePro'), (1, 'MQTT'), (2, 'KAFKA'), (3, 'DB')], default=0, verbose_name='转发类型'),
        ),
    ]
