# Generated by Django 2.2.2 on 2019-07-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('drive_name', models.CharField(max_length=30, verbose_name='驱动名称')),
                ('drive_path', models.CharField(max_length=150, verbose_name='驱动路径')),
                ('drive_remark', models.CharField(max_length=150, verbose_name='驱动描述')),
            ],
            options={
                'verbose_name': '网关子设备列表信息',
                'verbose_name_plural': '网关子设备列表信息',
                'db_table': 'gateway_drive_list',
            },
        ),
        migrations.CreateModel(
            name='ModbusRtuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('accord_name', models.CharField(max_length=30, verbose_name='协议名称')),
                ('accord_type', models.CharField(max_length=30, verbose_name='协议类型')),
                ('accord_address', models.CharField(max_length=30, verbose_name='协议地址位')),
                ('accord_com', models.CharField(max_length=30, verbose_name='协议串口号')),
                ('accord_botelv', models.CharField(default='9600', max_length=30, verbose_name='协议波特率')),
                ('accord_databit', models.SmallIntegerField(default=8, verbose_name='协议数据位')),
                ('accord_stopbit', models.SmallIntegerField(default=1, verbose_name='协议停止位')),
                ('accord_check', models.SmallIntegerField(choices=[(0, 'ODD'), (1, 'EVEN'), (2, '无校验')], default=2, verbose_name='协议奇偶校验')),
                ('accord_timeout', models.CharField(max_length=30, verbose_name='协议响应时间')),
                ('accord_readcycle', models.CharField(max_length=30, verbose_name='协议读取周期')),
                ('accord_cmd', models.CharField(max_length=2000, verbose_name='协议指令列表')),
                ('accord_rule', models.SmallIntegerField(choices=[(0, '长整型'), (1, 'IEEE-754')], default=0, verbose_name='协议数据转换公式')),
                ('is_show', models.SmallIntegerField(choices=[(0, '不显示至设备模板列表'), (1, '显示至设备模板列表')], default=0, verbose_name='显示标识')),
            ],
            options={
                'verbose_name': 'ModBusRtu协议配置模型',
                'verbose_name_plural': 'ModBusRtu协议配置模型',
                'db_table': 'gateway_modbusrtu_models',
            },
        ),
    ]
