# Generated by Django 2.2.2 on 2019-09-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qudong', '0006_auto_20190914_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttemplatertu',
            name='etr_format',
            field=models.SmallIntegerField(choices=[(0, 'Hex'), (1, 'Long-int'), (2, 'IEEE-754')], default=0, verbose_name='模板返回设备数据格式'),
        ),
    ]
